name: Test NestJS with library

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  TEST_WORKING_DIR: ${{ vars.TEST_WORKING_DIR }}

jobs:
  nest-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install nest dependencies
        run: npm clean-install
        working-directory: ${{ env.TEST_WORKING_DIR }}

      - name: Run build
        run: npm run build
        working-directory: ${{ env.TEST_WORKING_DIR }}

  nest-test:
    runs-on: ubuntu-latest
    needs: nest-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install nest dependencies
        run: npm clean-install
        working-directory: ${{ env.TEST_WORKING_DIR }}

      - name: Run tests
        run: npm run test
        working-directory: ${{ env.TEST_WORKING_DIR }}