name: Test NestJS with library

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  nest-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Change directory to test/nest
        run: cd test/nest_v11

      - name: Install nest dependencies
        run: npm clean-install

      - name: Run build
        run: npm run build

  nest-test:
    runs-on: ubuntu-latest
    needs: nest-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Change directory to test/nest
        run: cd test/nest_v11

      - name: Install nest dependencies
        run: npm clean-install

      - name: Run tests
        run: npm run test